server.port: 8888

spring:
  main.banner-mode: "off"
  profiles.active: live
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jta:
    enabled: true

  # Web console for integrated H2 database
  h2.console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: false

# Disable noisy logging
logging.level:
  nl.butads: debug
  org.springframework: WARN
  org.hibernate: WARN
  org.apache.catalina: WARN

